using Microsoft.EntityFrameworkCore;
using NetDwhProject.Core.Contracts;
namespace NetDwhProject.Infrastructure.Repositories;
public class AnalyticsRepository(DwDbContext db):IAnalyticsRepository{
public async Task<DateRange> ResolveDateRangeAsync(DateTime? from,DateTime? to){if(from.HasValue&&to.HasValue)return new(from.Value.Date,to.Value.Date.AddDays(1).AddTicks(-1));var min=await db.Sales.AsNoTracking().Where(x=>x.OrderDate!=null).MinAsync(x=>x.OrderDate);var max=await db.Sales.AsNoTracking().Where(x=>x.OrderDate!=null).MaxAsync(x=>x.OrderDate);var f=(from??min??new DateTime(2011,5,1)).Date;var t=(to??max??new DateTime(2011,6,30)).Date.AddDays(1).AddTicks(-1);return new(f,t);} 
private async Task<IQueryable<NetDwhProject.Core.DwEntities.Sales>> Base(DateTime? from,DateTime? to){var r=await ResolveDateRangeAsync(from,to);return db.Sales.AsNoTracking().Where(x=>x.OrderDate!=null&&x.OrderDate>=r.From&&x.OrderDate<=r.To);} 
public async Task<object> GetExecutiveKpisAsync(DateTime? from,DateTime? to){var q=await Base(from,to);var total=await q.SumAsync(x=>(decimal?)x.LineTotal)??0;var orders=await q.Where(x=>x.SalesOrderID!=null).Select(x=>x.SalesOrderID).Distinct().CountAsync();var units=await q.SumAsync(x=>(int?)(x.OrderQty??0))??0;var gp=await (from s in q join p in db.Products.AsNoTracking() on s.ProductID equals p.ProductKey into pj from p in pj.DefaultIfEmpty() select ((s.UnitPrice-(p==null?0:p.StandardCost))*(s.OrderQty??0))).SumAsync();return new{totalSales=total,grossProfit=gp,marginPct=total==0?0:gp/total,orders,units,aov=orders==0?0:total/orders};}
public async Task<IEnumerable<object>> GetSalesByMonthAsync(DateTime? from,DateTime? to){var q=await Base(from,to);return await q.GroupBy(x=>new{x.OrderDate!.Value.Year,x.OrderDate.Value.Month}).Select(g=>new{monthLabel=$"{g.Key.Year}-{g.Key.Month:00}",totalSales=g.Sum(x=>x.LineTotal)}).OrderBy(x=>x.monthLabel).ToListAsync<object>();}
public async Task<IEnumerable<object>> GetSalesByTerritoryGroupAsync(DateTime? from,DateTime? to){var q=await Base(from,to);return await (from s in q join t in db.Territory.AsNoTracking() on s.TerritoryID equals t.SalesTerritoryKey into tj from t in tj.DefaultIfEmpty() group s by t==null?"Unknown":t.SalesTerritoryGroup into g select new{territoryGroup=g.Key,totalSales=g.Sum(x=>x.LineTotal)}).ToListAsync<object>();}
public async Task<IEnumerable<object>> GetTopProductsAsync(DateTime? from,DateTime? to,int top){var q=await Base(from,to);return await (from s in q join p in db.Products.AsNoTracking() on s.ProductID equals p.ProductKey into pj from p in pj.DefaultIfEmpty() group s by new{Id=s.ProductID??0,Name=p==null?"Unknown":p.EnglishProductName} into g orderby g.Sum(x=>x.LineTotal) descending select new{productId=g.Key.Id,productName=g.Key.Name,totalSales=g.Sum(x=>x.LineTotal)}).Take(top).ToListAsync<object>();}
public async Task<object> GetOnlineOfflineShareAsync(DateTime? from,DateTime? to){var q=await Base(from,to);var online=await q.Where(x=>x.OnlineOrderFlag==true).SumAsync(x=>(decimal?)x.LineTotal)??0;var offline=await q.Where(x=>x.OnlineOrderFlag!=true).SumAsync(x=>(decimal?)x.LineTotal)??0;return new{onlineSales=online,offlineSales=offline};}
public async Task<IEnumerable<object>> GetMapSalesAsync(DateTime? from,DateTime? to){var q=await Base(from,to);return await (from s in q join t in db.Territory.AsNoTracking() on s.TerritoryID equals t.SalesTerritoryKey into tj from t in tj.DefaultIfEmpty() group s by new{code=t==null?null:t.CountryRegionCode,name=t==null?"Unknown":t.SalesTerritoryRegion} into g select new{countryRegionCode=g.Key.code,territoryName=g.Key.name,totalSales=g.Sum(x=>x.LineTotal)}).ToListAsync<object>();}
public async Task<IEnumerable<object>> GetOrderLineSnapshotAsync(DateTime? from,DateTime? to,int take){var q=await Base(from,to);return await (from s in q join c in db.Customer.AsNoTracking() on s.CustomerID equals c.CustomerKey into cj from c in cj.DefaultIfEmpty() join p in db.Products.AsNoTracking() on s.ProductID equals p.ProductKey into pj from p in pj.DefaultIfEmpty() join t in db.Territory.AsNoTracking() on s.TerritoryID equals t.SalesTerritoryKey into tj from t in tj.DefaultIfEmpty() join sm in db.ShipMethod.AsNoTracking() on s.ShipMethodID equals sm.ShipMethodID into sj from sm in sj.DefaultIfEmpty() select new{salesOrderNumber=s.SalesOrderNumber,orderDate=s.OrderDate,customerName=((c!=null?c.FirstName:"")+" "+(c!=null?c.LastName:"")).Trim(),productName=p==null?"Unknown":p.EnglishProductName,qty=s.OrderQty??0,lineTotal=s.LineTotal,territoryName=t==null?"Unknown":t.SalesTerritoryRegion,shipMethodName=sm==null?"Unknown":sm.ShipMethodName}).Take(take).ToListAsync<object>();}

public async Task<IEnumerable<object>> GetSalesByPeriodAsync(DateTime? from,DateTime? to,string granularity){var q=await Base(from,to);if(granularity=="day")return await q.GroupBy(x=>x.OrderDate!.Value.Date).Select(g=>new{periodLabel=g.Key.ToString("yyyy-MM-dd"),totalSales=g.Sum(x=>x.LineTotal),orders=g.Where(x=>x.SalesOrderID!=null).Select(x=>x.SalesOrderID).Distinct().Count()}).OrderBy(x=>x.periodLabel).ToListAsync<object>();return await q.GroupBy(x=>new{x.OrderDate!.Value.Year,x.OrderDate.Value.Month}).Select(g=>new{periodLabel=$"{g.Key.Year}-{g.Key.Month:00}",totalSales=g.Sum(x=>x.LineTotal),orders=g.Where(x=>x.SalesOrderID!=null).Select(x=>x.SalesOrderID).Distinct().Count()}).OrderBy(x=>x.periodLabel).ToListAsync<object>();}
public async Task<IEnumerable<object>> GetCumulativeSalesAsync(DateTime? from,DateTime? to,string granularity){var rows=(await GetSalesByPeriodAsync(from,to,granularity)).Cast<dynamic>().ToList();decimal run=0;var list=new List<object>();foreach(var r in rows){run+=(decimal)r.totalSales;list.Add(new{periodLabel=r.periodLabel,totalSales=r.totalSales,cumulativeSales=run});}return list;}
public async Task<object> GetKpisMtdYtdAsync(DateTime? asOf){var max=asOf??await db.Sales.AsNoTracking().Where(x=>x.OrderDate!=null).MaxAsync(x=>x.OrderDate)??DateTime.UtcNow;var mStart=new DateTime(max.Year,max.Month,1);var yStart=new DateTime(max.Year,1,1);var m=db.Sales.AsNoTracking().Where(x=>x.OrderDate!=null&&x.OrderDate>=mStart&&x.OrderDate<=max);var y=db.Sales.AsNoTracking().Where(x=>x.OrderDate!=null&&x.OrderDate>=yStart&&x.OrderDate<=max);var salesMTD=await m.SumAsync(x=>(decimal?)x.LineTotal)??0;var salesYTD=await y.SumAsync(x=>(decimal?)x.LineTotal)??0;var ordersMTD=await m.Where(x=>x.SalesOrderID!=null).Select(x=>x.SalesOrderID).Distinct().CountAsync();return new{salesMTD,salesYTD,ordersMTD,aovMTD=ordersMTD==0?0:salesMTD/ordersMTD};}
public async Task<IEnumerable<object>> GetTopCustomersAsync(DateTime? from,DateTime? to,int top){var q=await Base(from,to);return await (from s in q where s.CustomerID!=null group s by s.CustomerID into g orderby g.Sum(x=>x.LineTotal) descending select new{customerId=g.Key,customerName=$"Customer {g.Key}",totalSales=g.Sum(x=>x.LineTotal),orders=g.Where(x=>x.SalesOrderID!=null).Select(x=>x.SalesOrderID).Distinct().Count(),aov=(g.Where(x=>x.SalesOrderID!=null).Select(x=>x.SalesOrderID).Distinct().Count()==0?0:g.Sum(x=>x.LineTotal)/g.Where(x=>x.SalesOrderID!=null).Select(x=>x.SalesOrderID).Distinct().Count())}).Take(top).ToListAsync<object>();}
public async Task<object> GetCustomerKpisAsync(DateTime? from,DateTime? to){var q=await Base(from,to);var grp=await q.Where(x=>x.CustomerID!=null).GroupBy(x=>x.CustomerID).Select(g=>new{customer=g.Key,orders=g.Where(x=>x.SalesOrderID!=null).Select(x=>x.SalesOrderID).Distinct().Count()}).ToListAsync();var active=grp.Count;var repeat=grp.Count(x=>x.orders>1);return new{activeCustomers=active,repeatRate=active==0?0m:(decimal)repeat/active};}
public async Task<IEnumerable<object>> GetSalesByShipMethodAsync(DateTime? from,DateTime? to){var q=await Base(from,to);return await (from s in q join sm in db.ShipMethod.AsNoTracking() on s.ShipMethodID equals sm.ShipMethodID into sj from sm in sj.DefaultIfEmpty() group s by sm==null?"Unknown":sm.ShipMethodName into g select new{shipMethodName=g.Key,totalSales=g.Sum(x=>x.LineTotal),orders=g.Where(x=>x.SalesOrderID!=null).Select(x=>x.SalesOrderID).Distinct().Count()}).ToListAsync<object>();}

}
