using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.IdentityModel.Tokens;
using NetDwhProject.Core.Contracts;
namespace NetDwhProject.Infrastructure;
public interface IAuthService{Task<LoginResponse?> LoginAsync(LoginRequest req);Task<object?> MeAsync(int userId);} 
public class AuthService(OltpDbContext db,IConfiguration cfg):IAuthService{public async Task<LoginResponse?> LoginAsync(LoginRequest req){var u=await db.Users.Include(x=>x.UserRoles).ThenInclude(ur=>ur.Role).FirstOrDefaultAsync(x=>x.Username==req.Username);if(u==null||!BCrypt.Net.BCrypt.Verify(req.Password,u.PasswordHash))return null;var roles=u.UserRoles.Select(r=>r.Role!.Name).ToArray();var claims=new List<Claim>{new(JwtRegisteredClaimNames.Sub,u.Id.ToString()),new(ClaimTypes.Name,u.Username)};claims.AddRange(roles.Select(r=>new Claim(ClaimTypes.Role,r)));var key=new SymmetricSecurityKey(Encoding.UTF8.GetBytes(cfg["Jwt:Key"]!));var token=new JwtSecurityToken(claims:claims,expires:DateTime.UtcNow.AddHours(8),signingCredentials:new SigningCredentials(key,SecurityAlgorithms.HmacSha256));return new(new JwtSecurityTokenHandler().WriteToken(token),u.Username,roles);}public async Task<object?> MeAsync(int userId){var u=await db.Users.Include(x=>x.UserRoles).ThenInclude(x=>x.Role).FirstOrDefaultAsync(x=>x.Id==userId);return u==null?null:new{u.Id,u.Username,u.Email,roles=u.UserRoles.Select(x=>x.Role!.Name)};}}
public static class SeedData{public static async Task SeedAsync(OltpDbContext db){if(await db.Users.AnyAsync())return;var adminRole=new NetDwhProject.Core.Entities.Role{Name="Admin"};var userRole=new NetDwhProject.Core.Entities.Role{Name="User"};var admin=new NetDwhProject.Core.Entities.User{Username="admin",Email="admin@local",PasswordHash=BCrypt.Net.BCrypt.HashPassword("Admin123!")};var user=new NetDwhProject.Core.Entities.User{Username="user",Email="user@local",PasswordHash=BCrypt.Net.BCrypt.HashPassword("User123!")};db.Roles.AddRange(adminRole,userRole);db.Users.AddRange(admin,user);await db.SaveChangesAsync();db.UserRoles.AddRange(new NetDwhProject.Core.Entities.UserRole{UserId=admin.Id,RoleId=adminRole.Id},new NetDwhProject.Core.Entities.UserRole{UserId=admin.Id,RoleId=userRole.Id},new NetDwhProject.Core.Entities.UserRole{UserId=user.Id,RoleId=userRole.Id});await db.SaveChangesAsync();}}
