using Microsoft.EntityFrameworkCore;
using NetDwhProject.Core.Contracts;
using NetDwhProject.Core.Entities;
namespace NetDwhProject.Infrastructure.Repositories;
public class CategoryRepository(OltpDbContext db):ICategoryRepository{public async Task<Category> AddAsync(Category e){db.Categories.Add(e);await db.SaveChangesAsync();return e;}public async Task DeleteAsync(int id){var e=await db.Categories.FindAsync(id);if(e!=null){db.Categories.Remove(e);await db.SaveChangesAsync();}}public Task<IEnumerable<Category>> GetAllAsync()=>Task.FromResult<IEnumerable<Category>>(db.Categories.AsNoTracking().OrderBy(x=>x.Name).ToList());public Task<Category?> GetByIdAsync(int id)=>db.Categories.FindAsync(id).AsTask();public async Task UpdateAsync(Category e){db.Categories.Update(e);await db.SaveChangesAsync();}}
public class SubCategoryRepository(OltpDbContext db):ISubCategoryRepository{public async Task<SubCategory> AddAsync(SubCategory e){db.SubCategories.Add(e);await db.SaveChangesAsync();return e;}public async Task DeleteAsync(int id){var e=await db.SubCategories.FindAsync(id);if(e!=null){db.SubCategories.Remove(e);await db.SaveChangesAsync();}}public Task<IEnumerable<SubCategory>> GetAllAsync(int? categoryId){var q=db.SubCategories.AsNoTracking().Include(x=>x.Category).AsQueryable();if(categoryId.HasValue)q=q.Where(x=>x.CategoryId==categoryId.Value);return Task.FromResult<IEnumerable<SubCategory>>(q.OrderBy(x=>x.Name).ToList());}public Task<SubCategory?> GetByIdAsync(int id)=>db.SubCategories.FindAsync(id).AsTask();public async Task UpdateAsync(SubCategory e){db.SubCategories.Update(e);await db.SaveChangesAsync();}}
public class ProductRepository(OltpDbContext db):IProductRepository{public async Task<Product> AddAsync(Product e){db.Products.Add(e);await db.SaveChangesAsync();return e;}public async Task DeleteAsync(int id){var e=await db.Products.FindAsync(id);if(e!=null){db.Products.Remove(e);await db.SaveChangesAsync();}}public Task<IEnumerable<object>> GetAllProjectedAsync(int? categoryId,int? subCategoryId){var q=db.Products.AsNoTracking().Include(x=>x.SubCategory)!.ThenInclude(x=>x.Category).AsQueryable();if(subCategoryId.HasValue)q=q.Where(x=>x.SubCategoryId==subCategoryId);if(categoryId.HasValue)q=q.Where(x=>x.SubCategory!.CategoryId==categoryId);return Task.FromResult<IEnumerable<object>>(q.Select(p=>new{p.Id,p.Name,p.Price,p.StockQty,p.Sku,p.Description,p.IsActive,p.SubCategoryId,subCategoryName=p.SubCategory!.Name,categoryName=p.SubCategory.Category!.Name}).ToList<object>());}public Task<Product?> GetByIdAsync(int id)=>db.Products.FindAsync(id).AsTask();public async Task UpdateAsync(Product e){db.Products.Update(e);await db.SaveChangesAsync();}}
public class OrderRepository(OltpDbContext db):IOrderRepository{public async Task<Order> CreateAsync(int userId,CreateOrderRequest req){using var tx=await db.Database.BeginTransactionAsync();var products=await db.Products.Where(p=>req.Items.Select(i=>i.ProductId).Contains(p.Id)).ToDictionaryAsync(x=>x.Id);foreach(var it in req.Items){if(!products.TryGetValue(it.ProductId,out var p) || p.StockQty<it.Quantity)throw new InvalidOperationException($"Insufficient stock for {it.ProductId}");}
var sub=req.Items.Sum(i=>products[i.ProductId].Price*i.Quantity);var order=new Order{UserId=userId,OrderNumber=$"ORD-{DateTime.UtcNow:yyyyMMdd}-{Random.Shared.Next(1000,9999)}",SubTotal=sub,Tax=Math.Round(sub*0.1m,2),Shipping=sub>100?0:10,Total=Math.Round(sub*1.1m,2)+(sub>100?0:10),Notes=req.Notes};db.Orders.Add(order);await db.SaveChangesAsync();foreach(var it in req.Items){var p=products[it.ProductId];p.StockQty-=it.Quantity;db.OrderItems.Add(new OrderItem{OrderId=order.Id,ProductId=it.ProductId,Quantity=it.Quantity,UnitPrice=p.Price,LineTotal=p.Price*it.Quantity});}
await db.SaveChangesAsync();await tx.CommitAsync();return await db.Orders.Include(x=>x.Items).FirstAsync(x=>x.Id==order.Id);}public Task<Order?> GetByIdAsync(int id)=>db.Orders.Include(x=>x.Items).ThenInclude(i=>i.Product).FirstOrDefaultAsync(x=>x.Id==id);public async Task<IEnumerable<Order>> GetMyAsync(int userId)=>await db.Orders.AsNoTracking().Include(x=>x.Items).ThenInclude(i=>i.Product).Where(x=>x.UserId==userId).OrderByDescending(x=>x.OrderDate).ToListAsync();public async Task UpdateStatusAsync(int id,OrderStatus status){var e=await db.Orders.FindAsync(id)??throw new KeyNotFoundException();e.Status=status;await db.SaveChangesAsync();}}
